### ISSUE TITLE
Publish to PowerShell Gallery

### ISSUE THREAD

**Issue by alexmbaker** [Arnavion/PsFtpProvider#7] opened 2018-11-28 01:20 UTC
Excellent implementation as a PowerShell provider!  To get greater usage of this module and make it easier for others to install it could you publish it to the PowerShell Gallery?

Many thanks

**Comment by Arnavion** [comment] 2018-11-28 01:38
Duplicate of #4

**Closed as completed by Arnavion** 2018-11-28 01:38 UTC
